apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-role
  namespace: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io   
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: pipeline
