apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-cephfs-pvc
  namespace: pipeline
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
