apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newsapi-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/md-software/k8s_cd.git
    targetRevision: HEAD
    path: ocd9/newsapi/dev
  destination: 
    server: https://kubernetes.default.svc
    #https://10.102.11.177:6443
    namespace: pipeline

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
